import type { Metadata } from "next";

import "./globals.css";

import SubHeader from "../components/custom/subheader";
import { Navbar } from "../components/custom/navbar";
import Footer from "../components/custom/Footer";
import { Poppins } from "next/font/google";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-poppins",
});

export const metadata: Metadata = {
  title: "NeoCart",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={poppins.variable}>
      <body>
        <Navbar />
        <SubHeader />
        {children}
        <Footer />
      </body>
    </html>
  );
}
